module Mnist
  IMAGE_FILE_MAGIC_NUMBER: Integer
  LABEL_FILE_MAGIC_NUMBER: Integer

  class LoadImagesResult
    attr_reader images: Array[untyped]
    attr_reader num_images: Integer
    attr_reader num_rows: Integer
    attr_reader num_cols: Integer

    def initialize: (Array[untyped] images, Integer num_images, Integer num_rows, Integer num_cols) -> void
  end

  class LoadLabelsResult
    attr_reader labels: Array[Integer]
    attr_reader num_labels: Integer

    def initialize: (Array[Integer] labels, Integer num_labels) -> void
  end

  def self.load_images: (String idx_file) -> LoadImagesResult

  def self.load_labels: (String idx_file) -> LoadLabelsResult
end
