module Nn
  class LeNet5
    @conv1: Conv2d
    @pool1: MaxPool2d
    @conv2: Conv2d
    @pool2: MaxPool2d
    @fc1: Linear
    @fc2: Linear
    @fc3: Linear

    def initialize: () -> void

    def forward: (Array[Matrix] | Matrix input) -> Array[Float]
  end
end
