module Nn
  class Linear
    @in_features: Integer
    @out_features: Integer
    @weight: Matrix
    @bias: Array[Numeric]

    attr_reader in_features: Integer
    attr_reader out_features: Integer

    attr_accessor weight: Matrix
    attr_accessor bias: Array[Numeric]

    def initialize: (in_features: Integer, out_features: Integer) -> void

    def forward: (Array[Numeric] input) -> Array[Numeric]
  end
end
